### ISSUE TITLE
Cant get this to work

### ISSUE THREAD

**Issue by hooray4me** [elad-bar/ha-custom-components#1]
Is there anything special I need to do to get this work?

**Comment by elad-bar** [comment]
Was it solved?

thanks

**Comment by hooray4me** [comment]
no it wasn't. I ended up just adding the cameras individually to ha... Still use BI from the web.

**Comment by elad-bar** [comment]
can you try the latest version?
if it still doesn't work, please send me the logs

thanks

**Comment by hooray4me** [comment]
does the config file really start with configuration?
`**configuration:** 
  blueiris:
    #hostname / ip of BlueIris WebServer
    host: !secret blueiris_host`

**Comment by elad-bar** [comment]
No, it just to explain that it should be at the same level of all other domain under the root tag which is configuration

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hooray4me** [comment]
![image](https://user-images.githubusercontent.com/12399138/55821227-9b780480-5ac2-11e9-9d32-584a8e1790fc.png)

**Comment by elad-bar** [comment]
it lacks of the begining of the errors, can you cleanup the logs before starting the ha and after it fails copy that

in addition, it seems that there is a problem with your custom updater

**Comment by hooray4me** [comment]
Im going to manually install and then see what happens... BTW there is a typo in in your blueiris json file on line 17 /which.py should be switch.py

**Comment by hooray4me** [comment]
`2019-04-09 18:01:57 WARNING (MainThread) [homeassistant.loader] You are using a custom component for blueiris which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-04-09 18:01:57 WARNING (MainThread) [homeassistant.components.http] legacy_api_password support has been enabled. If you don't require it, remove the 'api_password' from your http config.
2019-04-09 18:01:58 WARNING (MainThread) [homeassistant.loader] You are using a custom component for cisco_ios.device_tracker which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-04-09 18:01:59 WARNING (MainThread) [homeassistant.loader] You are using a custom component for blueiris.binary_sensor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-04-09 18:01:59 WARNING (MainThread) [homeassistant.loader] You are using a custom component for blueiris.switch which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.`

`2019-04-09 18:01:59 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.blueiris.camera. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/home/rob/homeassistant/lib/python3.6/site-packages/homeassistant/loader.py", line 147, in _load_file
    module = importlib.import_module(path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/rob/.homeassistant/custom_components/blueiris/camera.py", line 14, in <module>
    from homeassistant.components.generic.camera import (CONF_LIMIT_REFETCH_TO_URL_CHANGE,
ModuleNotFoundError: No module named 'homeassistant.components.generic'
2019-04-09 18:01:59 ERROR (MainThread) [homeassistant.loader] Unable to find platform blueiris
2019-04-09 18:01:59 WARNING (MainThread) [homeassistant.loader] You are using a custom component for lennox.climate which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.`

**Comment by hooray4me** [comment]
Here's the latest log:
`2019-04-09 18:10:00 WARNING (MainThread) [homeassistant.components.http] legacy_api_password support has been enabled. If you don't require it, remove the 'api_password' from your http config.
2019-04-09 18:10:02 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.blueiris.switch. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/home/rob/homeassistant/lib/python3.6/site-packages/homeassistant/loader.py", line 147, in _load_file
    module = importlib.import_module(path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/rob/.homeassistant/custom_components/blueiris/__init__.py", line 18, in <module>
    from .blue_iris_data import BlueIrisData
  File "/home/rob/.homeassistant/custom_components/blueiris/blue_iris_data.py", line 4, in <module>
    from homeassistant.components.generic.camera import (CONF_STREAM_SOURCE, CONF_STILL_IMAGE_URL)
ModuleNotFoundError: No module named 'homeassistant.components.generic'
2019-04-09 18:10:02 ERROR (MainThread) [homeassistant.loader] Unable to find platform blueiris
2019-04-09 18:10:02 WARNING (MainThread) [homeassistant.loader] You are using a custom component for lennox.climate which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-04-09 18:10:02 WARNING (MainThread) [homeassistant.loader] You are using a custom component for cisco_ios.device_tracker which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-04-09 18:10:02 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.blueiris.binary_sensor. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/home/rob/homeassistant/lib/python3.6/site-packages/homeassistant/loader.py", line 147, in _load_file
    module = importlib.import_module(path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/rob/.homeassistant/custom_components/blueiris/__init__.py", line 18, in <module>
    from .blue_iris_data import BlueIrisData
  File "/home/rob/.homeassistant/custom_components/blueiris/blue_iris_data.py", line 4, in <module>
    from homeassistant.components.generic.camera import (CONF_STREAM_SOURCE, CONF_STILL_IMAGE_URL)
ModuleNotFoundError: No module named 'homeassistant.components.generic'
2019-04-09 18:10:02 ERROR (MainThread) [homeassistant.loader] Unable to find platform blueiris
2019-04-09 18:10:02 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.blueiris.camera. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/home/rob/homeassistant/lib/python3.6/site-packages/homeassistant/loader.py", line 147, in _load_file
    module = importlib.import_module(path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/rob/.homeassistant/custom_components/blueiris/__init__.py", line 18, in <module>
    from .blue_iris_data import BlueIrisData
  File "/home/rob/.homeassistant/custom_components/blueiris/blue_iris_data.py", line 4, in <module>
    from homeassistant.components.generic.camera import (CONF_STREAM_SOURCE, CONF_STILL_IMAGE_URL)
ModuleNotFoundError: No module named 'homeassistant.components.generic'
2019-04-09 18:10:02 ERROR (MainThread) [homeassistant.loader] Unable to find platform blueiris
2019-04-09 18:10:02 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.blueiris. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/home/rob/homeassistant/lib/python3.6/site-packages/homeassistant/loader.py", line 147, in _load_file
    module = importlib.import_module(path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/rob/.homeassistant/custom_components/blueiris/__init__.py", line 18, in <module>
    from .blue_iris_data import BlueIrisData
  File "/home/rob/.homeassistant/custom_components/blueiris/blue_iris_data.py", line 4, in <module>
    from homeassistant.components.generic.camera import (CONF_STREAM_SOURCE, CONF_STILL_IMAGE_URL)
ModuleNotFoundError: No module named 'homeassistant.components.generic'
2019-04-09 18:10:02 ERROR (MainThread) [homeassistant.loader] Unable to find component blueiris
2019-04-09 18:10:02 ERROR (MainThread) [homeassistant.setup] Setup failed for blueiris: Component not found.
2019-04-09 18:10:03 ERROR (SyncWorker_14) [homeassistant.components.sensor.rest] Error fetching data: <PreparedRequest [GET]> from http://localhost:5556/devices/bathroom/apps/tv.emby.embyatv/state failed with HTTPConnectionPool(host='localhost', port=5556): Max retries exceeded with url: /devices/bathroom/apps/tv.emby.embyatv/state (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7da400c518>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-04-09 18:10:03 ERROR (SyncWorker_7) [homeassistant.components.sensor.rest] Error fetching data: <PreparedRequest [GET]> from http://localhost:5556/devices/state/oliviaroom failed with HTTPConnectionPool(host='localhost', port=5556): Max retries exceeded with url: /devices/state/oliviaroom (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7da4053f98>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-04-09 18:10:03 ERROR (SyncWorker_8) [homeassistant.components.sensor.rest] Error fetching data: <PreparedRequest [GET]> from http://localhost:5556/devices/state/playroom failed with HTTPConnectionPool(host='localhost', port=5556): Max retries exceeded with url: /devices/state/playroom (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7d9c1b1278>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-04-09 18:10:03 ERROR (SyncWorker_4) [homeassistant.components.sensor.rest] Error fetching data: <PreparedRequest [GET]> from http://localhost:5556/devices/state/bathroom failed with HTTPConnectionPool(host='localhost', port=5556): Max retries exceeded with url: /devices/state/bathroom (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7d9c1b1be0>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-04-09 18:10:03 ERROR (SyncWorker_10) [homeassistant.components.sensor.rest] Error fetching data: <PreparedRequest [GET]> from http://localhost:5556/devices/oliviaroom/apps/tv.emby.embyatv/state failed with HTTPConnectionPool(host='localhost', port=5556): Max retries exceeded with url: /devices/oliviaroom/apps/tv.emby.embyatv/state (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7d9c1b6978>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-04-09 18:10:03 ERROR (SyncWorker_5) [homeassistant.components.sensor.rest] Error fetching data: <PreparedRequest [GET]> from http://localhost:5556/devices/playroom/apps/tv.emby.embyatv/state failed with HTTPConnectionPool(host='localhost', port=5556): Max retries exceeded with url: /devices/playroom/apps/tv.emby.embyatv/state (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7d9c1cb080>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-04-09 18:10:04 WARNING (MainThread) [homeassistant.components.sensor] Platform rest not ready yet. Retrying in 30 seconds.
2019-04-09 18:10:04 WARNING (MainThread) [homeassistant.components.sensor] Platform rest not ready yet. Retrying in 30 seconds.
2019-04-09 18:10:04 WARNING (MainThread) [homeassistant.components.sensor] Platform rest not ready yet. Retrying in 30 seconds.
2019-04-09 18:10:04 WARNING (MainThread) [homeassistant.components.sensor] Platform rest not ready yet. Retrying in 30 seconds.
2019-04-09 18:10:04 WARNING (MainThread) [homeassistant.components.sensor] Platform rest not ready yet. Retrying in 30 seconds.
2019-04-09 18:10:04 WARNING (MainThread) [homeassistant.components.sensor] Platform rest not ready yet. Retrying in 30 seconds.
`

**Comment by elad-bar** [comment]
what version of HA are you using?

**Comment by hooray4me** [comment]
0.88.2

**Comment by elad-bar** [comment]
component is aligned with latest version of HA v0.91, HA changed the structure of components that's why it didn't find the generic camera class

**Comment by elad-bar** [comment]
did you try that with latest version of HA?

**Comment by hooray4me** [comment]
no havent had time to make sure nothing else breaks...

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hooray4me** [comment]
I upgraded to .91. I am not able to get this to run from custom_updater.
`rob@ha:~/.homeassistant$ tail home-assistant.log
    for name, component in response.json().items():
  File "/home/rob/homeassistant/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 7 column 1 (char 6)
rob@ha:~/.homeassistant$ tail home-assistant.log
    for name, component in response.json().items():
  File "/home/rob/homeassistant/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 7 column 1 (char 6)
`
config:
`custom_updater:
  track:
    - components
  component_urls:
    - https://github.com/elad-bar/ha-custom-components/blob/master/blueiris.json
`

**Comment by hooray4me** [comment]
I manually updated the blueiris component. I can get the elements to show up in unused entities, but they do not work and I don't show a login in blueiris for my ha user.

No errors in the logs

_rob@ha:~/.homeassistant$ tail home-assistant.log
2019-04-23 14:53:52 WARNING (MainThread) [homeassistant.loader] You are using a custom component for blueiris which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.

2019-04-23 14:53:54 WARNING (MainThread) [homeassistant.loader] You are using a custom component for blueiris.binary_sensor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.

2019-04-23 14:53:55 WARNING (MainThread) [homeassistant.loader] You are using a custom component for blueiris.camera which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.

2019-04-23 14:53:55 WARNING (MainThread) [homeassistant.loader] You are using a custom component for myicomfort.climate which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.

2019-04-23 14:53:55 WARNING (MainThread) [homeassistant.loader] You are using a custom component for blueiris.switch which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant._

`blueiris:
  host: !secret blueiris_host
  port: !secret blueiris_port
  profile:
    armed: !secret blueiris_profile_armed
    unarmed: !secret blueiris_profile_unarmed
  username: !secret blueiris_api_username
  password: !secret blueiris_api_password
  mqtt:
    watchdog: BlueIris/[camera_id]/Connectivity
    motion: BlueIris/[camera_id]/Motion
  camera:
    - name: 'Olivias Room'
      id: olivia
      room: Upstairs
    - name: 'Noahs Room'
      id: noah
      room: Upstairs
    - name: 'Driveway'
      id: front
      room: Outside

blueiris_host: 172.17.17.75
blueiris_port: 80
blueiris_api_username: ha
blueiris_api_password: Bartlebee92
blueiris_profile_armed: 1
blueiris_profile_unarmed: 2

binary_sensor:
  - platform: blueiris

camera:
  - platform: blueiris

switch:
  - platform: blueiris`
![image](https://user-images.githubusercontent.com/12399138/56592747-dee96d00-65b0-11e9-9fcf-86961bd2d348.png)

![image](https://user-images.githubusercontent.com/12399138/56592758-e3ae2100-65b0-11e9-99df-9fa319592b0c.png)

**Comment by hooray4me** [comment]
It looks like the camera_proxy_stream api is not passing the blueiris credentials to the blueiris server. I see repeated login attempts without a username on the blueiris server.
![image](https://user-images.githubusercontent.com/12399138/56595993-4dc8c500-65b5-11e9-97a2-da9a92c09d61.png)
![image](https://user-images.githubusercontent.com/12399138/56596009-56b99680-65b5-11e9-91f5-b21b3565768e.png)

**Comment by hooray4me** [comment]
I've even set the logger level to debug for the blueiris components, but can't seem to get any more information from it.

`logger:
  default: critical
  logs:
    homeassistant.loader: warning
    homeassistant.components.blueiris: debug
    homeassistant.components.blueiris.camera: debug
    homeassistant.components.blueiris.binary_sensor: debug
    homeassistant.components.command_line.sensor: critical
    homeassistant.components.rest.sensor: critical`

**Comment by hooray4me** [comment]
I found that it won't work if you have use secure session keys enabled, which kinda stinks... with out it I don't get the nice UI3 login page or the security that comes from it.
![image](https://user-images.githubusercontent.com/12399138/56610809-f7b84980-65d5-11e9-9af6-52e6f7d555ff.png)

do you have any examples of what controls I can use for these cameras as ui cards?

**Comment by elad-bar** [comment]
I'm not using it, will check it in the weekend and see how to fix that security settings,
I'm using the motion sensor on top of the image from the camera,
It supports binary sensors of:
- Audio
- External
- Motion
- Watchdog

2 first just added thanks to @darkgrue 

In addition switch to control whether the BlueIris is armed or not:
- switch.bi_alerts

**Comment by darkgrue** [comment]
The `Use secure session keys and login page` uses `HTTP_DIGEST_AUTHENTICATION`. Which you probably don't want to use for two reasons. First, I see in other component integrations there are comments that "currently aiohttp only works with basic authentication". Also, if you wish to use Casting, I don't think Chromecast or Google Assistant supports passing authentication values (though you may get away with passing it in the URL, not clear on that - but you cannot perform HTTP Digest auth passing values in the URL, it *must* be in the header). So, to cast you'd need to set `Require from Non-LAN only`, and uncheck `Use secure session keys and login page`.

To be fair, HTTP Digest auth only gives you marginal better security, you'd be far better served setting up SSL (which appears to be another prerequisite for integrating with Google Assistant). I threw another Pi running a NGINX reverse-proxy in front of my Home Assistant and Blue Iris servers for that reason.

**Comment by darkgrue** [comment]
> do you have any examples of what controls I can use for these cameras as ui cards?
@hooray4me these are the Lovelace cards I use in my setup so far. I'm using one custom card `custom:vertical-stack-in-card` that would be a prerequisite. You can use a regular `vertical-stack` if you don't want to install the custom one, and it'd be perfectly functional. I think the custom one looks better.

Obviously some of the entity names would have to be edited to reflect your configuration, but it'll get you started on ideas on how to display your cards and sensors...
```
cards:
  - type: custom:vertical-stack-in-card
    cards:
      # System cameras
      - type: horizontal-stack
        cards:
          - type: custom:vertical-stack-in-card
#            title: All Cameras
            cards:
              - type: picture-entity
                entity: camera.bi_all
                name: All
                show_state: false
          - type: custom:vertical-stack-in-card
#            title: Camera Cycle
            cards:
              - type: picture-entity
                entity: camera.bi_cycle
                name: Cycle
                show_state: false
      # Blue Iris Armed / Disarm Profiles
      - type: entities
        title: Blue Iris
        show_header_toggle: false
        entities:
          - entity: switch.bi_alerts
            name: Arm / Disarm

  # Front Door camera
  - type: custom:vertical-stack-in-card
#    title: Front Door
    cards:
      - type: picture-entity
        entity: camera.bi_front_door
        name: Front Door
        show_state: false
      - type: glance
        entities:           
          - entity: binary_sensor.bi_front_door_motion
            name: Motion
          - entity: binary_sensor.bi_front_door_audio
            name: Audio
          - entity: binary_sensor.bi_front_door_watchdog
            name: Watchdog

  # Front Drive camera
  - type: custom:vertical-stack-in-card
#    title: Front Drive
    cards:
      - type: picture-entity
        entity: camera.bi_front_drive
        name: Front Drive
        show_state: false
      - type: glance
        entities:
          - entity: binary_sensor.bi_front_drive_motion
            name: Motion
          - entity: binary_sensor.bi_front_drive_audio
            name: Audio
          - entity: binary_sensor.bi_front_drive_watchdog
            name: Watchdog  

  # Garage camera
  - type: custom:vertical-stack-in-card
#    title: Garage
    cards:
      - type: picture-entity
        entity: camera.bi_garage
        name: Garage
        show_state: false
      - type: glance
        entities:
          - entity: binary_sensor.bi_garage_motion
            name: Motion
          - entity: binary_sensor.bi_garage_audio
            name: Audio
          - entity: binary_sensor.bi_garage_watchdog
            name: Watchdog
```

**Comment by hooray4me** [comment]
@darkgrue how do I get audio and watchdog into my configuration?

**Comment by darkgrue** [comment]
> @darkgrue how do I get audio and watchdog into my configuration?

I just put in a pull request (#7) with updated documentation and screenshots that shows the necessary configuration in Blue Iris to support the new MQTT messages. You can see [the new documentation](https://github.com/darkgrue/ha-custom-components/blob/master/BlueIris.md) on my fork (it's not real practical to try an read it through the pull request, I think).

The new alerts only work with cameras that support it, of course. If the `AUDIO` and `EXTERNAL` events don't work in BI with your camera, they won't ever trigger a MQTT message for those events, either.

**Comment by hooray4me** [comment]
and is there a way to limit the cameras in the cycle? I have 3 cams, one is outside and the other 2 are for my  kids rooms when they are sleeping. I'd like to cycle just 2 of the 3

**Comment by hooray4me** [comment]
also there is a typo in the blueiris.json for the customer updater. switch.yaml is witch.yaml.

**Comment by darkgrue** [comment]
> and is there a way to limit the cameras in the cycle? I have 3 cams, one is outside and the other 2 are for my kids rooms when they are sleeping. I'd like to cycle just 2 of the 3

The "All" and "Cycle" cameras are internally-generated views created by Blue Iris. I didn't see any options to specify which cameras get included in those views. But that configuration would be done on the BI side, if it was possible.

**Comment by hooray4me** [comment]
The only other functionality I'd like to see is a toggle for infrared...

**Comment by hooray4me** [comment]
@darkgrue How do the additional binary sensors get created? I can see the mqtt topic come thru when I unplug the camera... but a binary sensor isn't getting created...
